version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - netflix_network

  movie-catalog:
    image: alonithuji/netflix-movie-catalog:0.0.1
    expose:
      - "8080"
    networks:
      - netflix_network

  frontend:
    image: alonithuji/netflix-frontend:0.0.1
    environment:
      - MOVIE_CATALOG_SERVICE=http://movie-catalog:8080
    expose:
      - "3000"
    depends_on:
      - movie-catalog
    networks:
      - netflix_network

networks:
  netflix_network:
    driver: bridge
